//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_COMPANY_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RA42_COMPANY_MST()
        {
            this.RA42_COMPANY_PASS_DTL = new HashSet<RA42_COMPANY_PASS_DTL>();
            this.RA42_CONTRACTING_COMPANIES_PASS_DTL = new HashSet<RA42_CONTRACTING_COMPANIES_PASS_DTL>();
            this.RA42_PERMITS_DTL = new HashSet<RA42_PERMITS_DTL>();
            this.RA42_SECURITY_PASS_DTL = new HashSet<RA42_SECURITY_PASS_DTL>();
            this.RA42_VECHILE_PASS_DTL = new HashSet<RA42_VECHILE_PASS_DTL>();
            this.RA42_VISITOR_PASS_DTL = new HashSet<RA42_VISITOR_PASS_DTL>();
        }
    
        public int COMPANY_CODE { get; set; }
        public Nullable<int> UNIT_CODE { get; set; }
        public Nullable<int> STATION_CODE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_NAME_E { get; set; }
        public Nullable<int> COMPANY_TYPE_CODE { get; set; }
        public Nullable<int> PHONE_NUMBER { get; set; }
        public Nullable<int> GSM { get; set; }
        public string WEBSITE { get; set; }
        public string REMARKS { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_COMPANY_PASS_DTL> RA42_COMPANY_PASS_DTL { get; set; }
        public virtual RA42_COMPANY_TYPE_MST RA42_COMPANY_TYPE_MST { get; set; }
        public virtual RA42_STATIONS_MST RA42_STATIONS_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_CONTRACTING_COMPANIES_PASS_DTL> RA42_CONTRACTING_COMPANIES_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_PERMITS_DTL> RA42_PERMITS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_SECURITY_PASS_DTL> RA42_SECURITY_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_VECHILE_PASS_DTL> RA42_VECHILE_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_VISITOR_PASS_DTL> RA42_VISITOR_PASS_DTL { get; set; }
    }
}
