//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_ACCESS_TYPE_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RA42_ACCESS_TYPE_MST()
        {
            this.RA42_ACCESS_SELECT_MST = new HashSet<RA42_ACCESS_SELECT_MST>();
            this.RA42_AUTHORIZATION_PASS_DTL = new HashSet<RA42_AUTHORIZATION_PASS_DTL>();
            this.RA42_COMPANY_PASS_DTL = new HashSet<RA42_COMPANY_PASS_DTL>();
            this.RA42_FAMILY_PASS_DTL = new HashSet<RA42_FAMILY_PASS_DTL>();
            this.RA42_PERMITS_DTL = new HashSet<RA42_PERMITS_DTL>();
            this.RA42_SECURITY_PASS_DTL = new HashSet<RA42_SECURITY_PASS_DTL>();
            this.RA42_VECHILE_PASS_DTL = new HashSet<RA42_VECHILE_PASS_DTL>();
            this.RA42_AIR_CREW_PASS_DTL = new HashSet<RA42_AIR_CREW_PASS_DTL>();
            this.RA42_CARD_DESIGN_DTL = new HashSet<RA42_CARD_DESIGN_DTL>();
            this.RA42_CARD_FOR_MST = new HashSet<RA42_CARD_FOR_MST>();
            this.RA42_COMMENTS_MST = new HashSet<RA42_COMMENTS_MST>();
            this.RA42_CONTRACTING_COMPANIES_PASS_DTL = new HashSet<RA42_CONTRACTING_COMPANIES_PASS_DTL>();
            this.RA42_DOCUMENTS_ACCESS_MST = new HashSet<RA42_DOCUMENTS_ACCESS_MST>();
            this.RA42_ENTER_EXIT_REGISTERATION_DTL = new HashSet<RA42_ENTER_EXIT_REGISTERATION_DTL>();
            this.RA42_FILES_MST = new HashSet<RA42_FILES_MST>();
            this.RA42_MEMBERS_DTL = new HashSet<RA42_MEMBERS_DTL>();
            this.RA42_PRINT_MST = new HashSet<RA42_PRINT_MST>();
            this.RA42_TEMPRORY_COMPANY_PASS_DTL = new HashSet<RA42_TEMPRORY_COMPANY_PASS_DTL>();
            this.RA42_TRAINEES_PASS_DTL = new HashSet<RA42_TRAINEES_PASS_DTL>();
            this.RA42_TRANSACTION_DTL = new HashSet<RA42_TRANSACTION_DTL>();
            this.RA42_VECHILE_VIOLATION_DTL = new HashSet<RA42_VECHILE_VIOLATION_DTL>();
            this.RA42_VISITOR_PASS_DTL = new HashSet<RA42_VISITOR_PASS_DTL>();
            this.RA42_ZONE_MASTER_MST = new HashSet<RA42_ZONE_MASTER_MST>();
        }
    
        public int ACCESS_TYPE_CODE { get; set; }
        public string ACCESS_TYPE { get; set; }
        public string ACCESS_TYPE_E { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> ACCESS_SECRET_CODE { get; set; }
        public string ICON { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_ACCESS_SELECT_MST> RA42_ACCESS_SELECT_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_AUTHORIZATION_PASS_DTL> RA42_AUTHORIZATION_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_COMPANY_PASS_DTL> RA42_COMPANY_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_FAMILY_PASS_DTL> RA42_FAMILY_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_PERMITS_DTL> RA42_PERMITS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_SECURITY_PASS_DTL> RA42_SECURITY_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_VECHILE_PASS_DTL> RA42_VECHILE_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_AIR_CREW_PASS_DTL> RA42_AIR_CREW_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_CARD_DESIGN_DTL> RA42_CARD_DESIGN_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_CARD_FOR_MST> RA42_CARD_FOR_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_COMMENTS_MST> RA42_COMMENTS_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_CONTRACTING_COMPANIES_PASS_DTL> RA42_CONTRACTING_COMPANIES_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_DOCUMENTS_ACCESS_MST> RA42_DOCUMENTS_ACCESS_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_ENTER_EXIT_REGISTERATION_DTL> RA42_ENTER_EXIT_REGISTERATION_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_FILES_MST> RA42_FILES_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_MEMBERS_DTL> RA42_MEMBERS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_PRINT_MST> RA42_PRINT_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_TEMPRORY_COMPANY_PASS_DTL> RA42_TEMPRORY_COMPANY_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_TRAINEES_PASS_DTL> RA42_TRAINEES_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_TRANSACTION_DTL> RA42_TRANSACTION_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_VECHILE_VIOLATION_DTL> RA42_VECHILE_VIOLATION_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_VISITOR_PASS_DTL> RA42_VISITOR_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_ZONE_MASTER_MST> RA42_ZONE_MASTER_MST { get; set; }
    }
}
