//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_CARD_DESIGN_DTL
    {
        public int CARD_CODE { get; set; }
        public Nullable<int> ACCESS_TYPE_CODE { get; set; }
        public Nullable<int> CARD_FOR_CODE { get; set; }
        public Nullable<int> FORCE_ID { get; set; }
        public string BASE64_ENCODE_FRONT { get; set; }
        public string BASE64_ENCODE_BACK { get; set; }
        public string BASE64_ENCODE_TEMP { get; set; }
        public string REMARKS { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
    
        public virtual RA42_ACCESS_TYPE_MST RA42_ACCESS_TYPE_MST { get; set; }
        public virtual RA42_CARD_FOR_MST RA42_CARD_FOR_MST { get; set; }
        public virtual RA42_FORCES_MST RA42_FORCES_MST { get; set; }
    }
}
