//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_SLIDER_DTL
    {
        public int SLIDER_ID { get; set; }
        public string SLIDER_IMAGE { get; set; }
        public string SLIDER_TITLE_A { get; set; }
        public string SLIDER_TITLE_E { get; set; }
        public string DESCRIPTION_A { get; set; }
        public string DESCRIPTION_E { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
    }
}
