//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_FILE_TYPE_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RA42_FILE_TYPE_MST()
        {
            this.RA42_DOCUMENTS_ACCESS_MST = new HashSet<RA42_DOCUMENTS_ACCESS_MST>();
            this.RA42_FILE_CARD_MST = new HashSet<RA42_FILE_CARD_MST>();
            this.RA42_FILE_FORCES_MST = new HashSet<RA42_FILE_FORCES_MST>();
            this.RA42_FILE_FORCES_MST1 = new HashSet<RA42_FILE_FORCES_MST>();
            this.RA42_FILES_MST = new HashSet<RA42_FILES_MST>();
        }
    
        public int FILE_TYPE_CODE { get; set; }
        public string FILE_TYPE { get; set; }
        public string FILE_TYPE_E { get; set; }
        public Nullable<int> FILE_NOTE_CODE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_DOCUMENTS_ACCESS_MST> RA42_DOCUMENTS_ACCESS_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_FILE_CARD_MST> RA42_FILE_CARD_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_FILE_FORCES_MST> RA42_FILE_FORCES_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_FILE_FORCES_MST> RA42_FILE_FORCES_MST1 { get; set; }
        public virtual RA42_FILE_NOTE_TYPE_MST RA42_FILE_NOTE_TYPE_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_FILES_MST> RA42_FILES_MST { get; set; }
    }
}
