//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_SEARCH_MST
    {
        public int SEARCH_CODE { get; set; }
        public string SEARCH_TEXT { get; set; }
        public Nullable<System.DateTime> SEARCH_DATE { get; set; }
        public string SEARCH_BY { get; set; }
    }
}
