//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_VECHILE_VIOLATION_DTL
    {
        public int VECHILE_VIOLATION_CODE { get; set; }
        public Nullable<int> VIOLATION_CODE { get; set; }
        public string VIOLATION_DESC { get; set; }
        public Nullable<double> VIOLATION_PRICE { get; set; }
        public Nullable<System.DateTime> VIOLATION_DATE { get; set; }
        public string VIOLATION_BY { get; set; }
        public Nullable<bool> PREVENT { get; set; }
        public Nullable<int> ACCESS_ROW_CODE { get; set; }
        public Nullable<int> ACCESS_TYPE_CODE { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
    
        public virtual RA42_ACCESS_TYPE_MST RA42_ACCESS_TYPE_MST { get; set; }
        public virtual RA42_VIOLATIONS_MST RA42_VIOLATIONS_MST { get; set; }
    }
}
