//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_GENERAL_USERS_MST
    {
        public int GENERAL_USER_CODE { get; set; }
        public string SERVICE_NUMBER { get; set; }
        public string NAME_A { get; set; }
        public string UNIT_A { get; set; }
        public Nullable<int> UNIT_CODE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
    }
}
