//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_CARD_FOR_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RA42_CARD_FOR_MST()
        {
            this.RA42_AIR_CREW_PASS_DTL = new HashSet<RA42_AIR_CREW_PASS_DTL>();
            this.RA42_AIR_CREW_PASS_DTL1 = new HashSet<RA42_AIR_CREW_PASS_DTL>();
            this.RA42_AUTHORIZATION_PASS_DTL = new HashSet<RA42_AUTHORIZATION_PASS_DTL>();
            this.RA42_CARD_DESIGN_DTL = new HashSet<RA42_CARD_DESIGN_DTL>();
            this.RA42_COMPANY_PASS_DTL = new HashSet<RA42_COMPANY_PASS_DTL>();
            this.RA42_CONTRACTING_COMPANIES_PASS_DTL = new HashSet<RA42_CONTRACTING_COMPANIES_PASS_DTL>();
            this.RA42_FAMILY_PASS_DTL = new HashSet<RA42_FAMILY_PASS_DTL>();
            this.RA42_FILE_CARD_MST = new HashSet<RA42_FILE_CARD_MST>();
            this.RA42_PERMITS_DTL = new HashSet<RA42_PERMITS_DTL>();
            this.RA42_SECURITY_PASS_DTL = new HashSet<RA42_SECURITY_PASS_DTL>();
            this.RA42_TRAINEES_PASS_DTL = new HashSet<RA42_TRAINEES_PASS_DTL>();
            this.RA42_VECHILE_PASS_DTL = new HashSet<RA42_VECHILE_PASS_DTL>();
            this.RA42_VISITOR_PASS_DTL = new HashSet<RA42_VISITOR_PASS_DTL>();
        }
    
        public int CARD_FOR_CODE { get; set; }
        public Nullable<int> ACCESS_TYPE_CODE { get; set; }
        public string FORCES_IDS { get; set; }
        public string CARD_FOR_A { get; set; }
        public string CARD_FOR_E { get; set; }
        public string CARD_SECRET_CODE { get; set; }
        public Nullable<bool> WITH_CAR { get; set; }
        public string REMARKS { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
    
        public virtual RA42_ACCESS_TYPE_MST RA42_ACCESS_TYPE_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_AIR_CREW_PASS_DTL> RA42_AIR_CREW_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_AIR_CREW_PASS_DTL> RA42_AIR_CREW_PASS_DTL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_AUTHORIZATION_PASS_DTL> RA42_AUTHORIZATION_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_CARD_DESIGN_DTL> RA42_CARD_DESIGN_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_COMPANY_PASS_DTL> RA42_COMPANY_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_CONTRACTING_COMPANIES_PASS_DTL> RA42_CONTRACTING_COMPANIES_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_FAMILY_PASS_DTL> RA42_FAMILY_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_FILE_CARD_MST> RA42_FILE_CARD_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_PERMITS_DTL> RA42_PERMITS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_SECURITY_PASS_DTL> RA42_SECURITY_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_TRAINEES_PASS_DTL> RA42_TRAINEES_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_VECHILE_PASS_DTL> RA42_VECHILE_PASS_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_VISITOR_PASS_DTL> RA42_VISITOR_PASS_DTL { get; set; }
    }
}
