//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_FORCES_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RA42_FORCES_MST()
        {
            this.RA42_CARD_DESIGN_DTL = new HashSet<RA42_CARD_DESIGN_DTL>();
            this.RA42_FILE_FORCES_MST = new HashSet<RA42_FILE_FORCES_MST>();
            this.RA42_FILE_FORCES_MST1 = new HashSet<RA42_FILE_FORCES_MST>();
            this.RA42_MANAGER_SIGNATURE_MST = new HashSet<RA42_MANAGER_SIGNATURE_MST>();
            this.RA42_SECURITY_CAVEATES_DTL = new HashSet<RA42_SECURITY_CAVEATES_DTL>();
            this.RA42_STATIONS_MST = new HashSet<RA42_STATIONS_MST>();
            this.RA42_TRANSACTION_TYPE_MST = new HashSet<RA42_TRANSACTION_TYPE_MST>();
        }
    
        public int FORCE_ID { get; set; }
        public string FORCE_NAME_A { get; set; }
        public string FORCE_NAME_E { get; set; }
        public string DIRECTORATE_A { get; set; }
        public string DIRECTORATE_E { get; set; }
        public string FORCE_CODE { get; set; }
        public string LOGO { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_CARD_DESIGN_DTL> RA42_CARD_DESIGN_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_FILE_FORCES_MST> RA42_FILE_FORCES_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_FILE_FORCES_MST> RA42_FILE_FORCES_MST1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_MANAGER_SIGNATURE_MST> RA42_MANAGER_SIGNATURE_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_SECURITY_CAVEATES_DTL> RA42_SECURITY_CAVEATES_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_STATIONS_MST> RA42_STATIONS_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_TRANSACTION_TYPE_MST> RA42_TRANSACTION_TYPE_MST { get; set; }
    }
}
