//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_ZONE_AREA_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RA42_ZONE_AREA_MST()
        {
            this.RA42_ZONE_SUB_AREA_MST = new HashSet<RA42_ZONE_SUB_AREA_MST>();
            this.RA42_ZONE_MASTER_MST = new HashSet<RA42_ZONE_MASTER_MST>();
        }
    
        public int ZONE_CODE { get; set; }
        public string ZONE_TYPE { get; set; }
        public Nullable<int> ZONE_NUMBER { get; set; }
        public string ZONE_NAME { get; set; }
        public string ZONE_NAME_E { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> UNIT_CODE { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
        public Nullable<int> STATION_CODE { get; set; }
    
        public virtual RA42_STATIONS_MST RA42_STATIONS_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_ZONE_SUB_AREA_MST> RA42_ZONE_SUB_AREA_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_ZONE_MASTER_MST> RA42_ZONE_MASTER_MST { get; set; }
    }
}
