//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_TRANSACTION_TYPE_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RA42_TRANSACTION_TYPE_MST()
        {
            this.RA42_TRANSACTION_DTL = new HashSet<RA42_TRANSACTION_DTL>();
        }
    
        public int TRANSACTION_TYPE_CODE { get; set; }
        public string TRANSACTION_NAME_A { get; set; }
        public string TRANSACTION_NAME_E { get; set; }
        public Nullable<int> FORCE_ID { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public string REMARKS { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
    
        public virtual RA42_FORCES_MST RA42_FORCES_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_TRANSACTION_DTL> RA42_TRANSACTION_DTL { get; set; }
    }
}
