//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_PRINT_MST
    {
        public int PRINT_CODE { get; set; }
        public Nullable<int> ACCESS_TYPE_CODE { get; set; }
        public Nullable<int> PASS_ROW_CODE { get; set; }
        public string PRINT_TYPE { get; set; }
        public string PRINT_BY { get; set; }
        public Nullable<System.DateTime> PRINT_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
    
        public virtual RA42_ACCESS_TYPE_MST RA42_ACCESS_TYPE_MST { get; set; }
    }
}
