//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_WORKFLOW_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RA42_WORKFLOW_MST()
        {
            this.RA42_WORKFLOW_RESPONSIBLE_MST = new HashSet<RA42_WORKFLOW_RESPONSIBLE_MST>();
        }
    
        public int WORKFLOWID { get; set; }
        public string STEP_NAME { get; set; }
        public string STEP_NAME_E { get; set; }
        public Nullable<int> WORKFLOW_SECRET_CODE { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RA42_WORKFLOW_RESPONSIBLE_MST> RA42_WORKFLOW_RESPONSIBLE_MST { get; set; }
    }
}
