//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClearanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA42_RELATIVE_MST
    {
        public int RELATIVE_CODE { get; set; }
        public Nullable<int> FAMILY_CODE { get; set; }
        public Nullable<int> RELATIVE_TYPE_CODE { get; set; }
        public Nullable<int> CIVIL_NUMBER { get; set; }
        public string RELATIVE_NAME { get; set; }
        public string PERSONAL_IMAGE { get; set; }
        public Nullable<int> IDENTITY_CODE { get; set; }
        public Nullable<int> GENDER_ID { get; set; }
        public string REMARKS { get; set; }
        public Nullable<bool> ISPRINTED { get; set; }
        public Nullable<bool> DLT_STS { get; set; }
        public string CRD_BY { get; set; }
        public Nullable<System.DateTime> CRD_DT { get; set; }
        public string UPD_BY { get; set; }
        public Nullable<System.DateTime> UPD_DT { get; set; }
    
        public virtual RA42_FAMILY_PASS_DTL RA42_FAMILY_PASS_DTL { get; set; }
        public virtual RA42_GENDERS_MST RA42_GENDERS_MST { get; set; }
        public virtual RA42_IDENTITY_MST RA42_IDENTITY_MST { get; set; }
        public virtual RA42_RELATIVE_TYPE_MST RA42_RELATIVE_TYPE_MST { get; set; }
    }
}
