name: Generate DocFX Documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install DocFX
      run: |
        wget https://github.com/dotnet/docfx/releases/latest/download/docfx-linux-x64.zip
        unzip docfx-linux-x64.zip -d docfx
        echo "$(pwd)/docfx" >> $GITHUB_PATH

    - name: Build Documentation
      run: docfx/docfx init -q && docfx/docfx build

    - name: Upload Documentation as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docfx-docs
        path: _site
