//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Passes
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Passes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurityClearanceWebApp.Resources.Passes", typeof(Passes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفويض الأمني.
        /// </summary>
        public static string access_type_ar {
            get {
                return ResourceManager.GetString("access_type_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORIZATION PASS.
        /// </summary>
        public static string access_type_en {
            get {
                return ResourceManager.GetString("access_type_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجراءات.
        /// </summary>
        public static string ACTIONS_ar {
            get {
                return ResourceManager.GetString("ACTIONS_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIONS.
        /// </summary>
        public static string ACTIONS_en {
            get {
                return ResourceManager.GetString("ACTIONS_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفويض الأمني.
        /// </summary>
        public static string controllerName_ar {
            get {
                return ResourceManager.GetString("controllerName_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORIZATION PASS.
        /// </summary>
        public static string controllerName_en {
            get {
                return ResourceManager.GetString("controllerName_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنشئ.
        /// </summary>
        public static string CRD_BY_ar {
            get {
                return ResourceManager.GetString("CRD_BY_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATED BY.
        /// </summary>
        public static string CRD_BY_en {
            get {
                return ResourceManager.GetString("CRD_BY_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        public static string CRD_DT_ar {
            get {
                return ResourceManager.GetString("CRD_DT_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATED DATE.
        /// </summary>
        public static string CRD_DT_en {
            get {
                return ResourceManager.GetString("CRD_DT_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string REMARKS_ar {
            get {
                return ResourceManager.GetString("REMARKS_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMARKS.
        /// </summary>
        public static string REMARKS_en {
            get {
                return ResourceManager.GetString("REMARKS_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدث البيانات.
        /// </summary>
        public static string UPD_BY_ar {
            get {
                return ResourceManager.GetString("UPD_BY_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED BY.
        /// </summary>
        public static string UPD_BY_en {
            get {
                return ResourceManager.GetString("UPD_BY_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التحديث.
        /// </summary>
        public static string UPD_DT_ar {
            get {
                return ResourceManager.GetString("UPD_DT_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED DATE.
        /// </summary>
        public static string UPD_DT_en {
            get {
                return ResourceManager.GetString("UPD_DT_en", resourceCulture);
            }
        }
    }
}
