//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurityClearanceWebApp.Resources.SettingsE", typeof(SettingsE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجراءات.
        /// </summary>
        public static string ACTIONS_ar {
            get {
                return ResourceManager.GetString("ACTIONS_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIONS.
        /// </summary>
        public static string ACTIONS_en {
            get {
                return ResourceManager.GetString("ACTIONS_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سير العمل.
        /// </summary>
        public static string controller_Name_ar {
            get {
                return ResourceManager.GetString("controller_Name_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKFLOW.
        /// </summary>
        public static string controller_Name_en {
            get {
                return ResourceManager.GetString("controller_Name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنشئ.
        /// </summary>
        public static string CRD_BY_ar {
            get {
                return ResourceManager.GetString("CRD_BY_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATED BY.
        /// </summary>
        public static string CRD_BY_en {
            get {
                return ResourceManager.GetString("CRD_BY_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        public static string CRD_DT_ar {
            get {
                return ResourceManager.GetString("CRD_DT_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATED DATE.
        /// </summary>
        public static string CRD_DT_en {
            get {
                return ResourceManager.GetString("CRD_DT_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string NAME_ar {
            get {
                return ResourceManager.GetString("NAME_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string NAME_en {
            get {
                return ResourceManager.GetString("NAME_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string REMARKS_ar {
            get {
                return ResourceManager.GetString("REMARKS_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMARKS.
        /// </summary>
        public static string REMARKS_en {
            get {
                return ResourceManager.GetString("REMARKS_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم العسكري.
        /// </summary>
        public static string SERVICE_NUMBER_ar {
            get {
                return ResourceManager.GetString("SERVICE_NUMBER_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE NUMBER.
        /// </summary>
        public static string SERVICE_NUMBER_en {
            get {
                return ResourceManager.GetString("SERVICE_NUMBER_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القاعدة.
        /// </summary>
        public static string UNIT_CODE_ar {
            get {
                return ResourceManager.GetString("UNIT_CODE_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIT.
        /// </summary>
        public static string UNIT_CODE_en {
            get {
                return ResourceManager.GetString("UNIT_CODE_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدث البيانات.
        /// </summary>
        public static string UPD_BY_ar {
            get {
                return ResourceManager.GetString("UPD_BY_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED BY.
        /// </summary>
        public static string UPD_BY_en {
            get {
                return ResourceManager.GetString("UPD_BY_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التحديث.
        /// </summary>
        public static string UPD_DT_ar {
            get {
                return ResourceManager.GetString("UPD_DT_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED DATE.
        /// </summary>
        public static string UPD_DT_en {
            get {
                return ResourceManager.GetString("UPD_DT_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجهة إلى.
        /// </summary>
        public static string WORKFLOW_TYPE_ar {
            get {
                return ResourceManager.GetString("WORKFLOW_TYPE_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKFLOW TYPE.
        /// </summary>
        public static string WORKFLOW_TYPE_en {
            get {
                return ResourceManager.GetString("WORKFLOW_TYPE_en", resourceCulture);
            }
        }
    }
}
